# Generated by Django 5.0 on 2023-12-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookListAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='books',
            index=models.Index(fields=['price'], name='BookListAPI_price_f504e4_idx'),
        ),
    ]
